Repository openshift/jenkins-openshift-login-plugin, pull requests merged in 2022-10, with the labels that each got.

#135 Align approvers and owners with openshift/jenkins
  OWNERS
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#137 chore(README): fix typo
  README.md
Labels: approved, lgtm, needs-ok-to-test, qe-approved, px-approved, docs-approved

#138 OCPBUGS-903: Bump google-oauth-client dependency to 1.34.1
  pom.xml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug
